version: "3"
services:
  server:
    container_name: air
    build:
      dockerfile: Dockerfile.dev
    working_dir: /app
    ports:
      - 8080:8080
    volumes:
      - ./:/app
      - ./config.json:/app/config.json
    networks:
      - server

networks: 
  server:
    driver: bridge